<<<<<<< HEAD
# Generated by Django 2.1.15 on 2020-08-14 07:44
=======
# Generated by Django 2.1.15 on 2020-08-12 07:38
>>>>>>> 37eb06a578ddc41ab4f9b67f9ac734e6ce80f0e4

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('volume_ml', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='IngredientCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_alcohol', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('author', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('idDrink', models.IntegerField(default=9999)),
                ('strDrink', models.CharField(max_length=100)),
                ('strInstructions', models.TextField(max_length=300)),
                ('strAlcoholic', models.BooleanField(default='true')),
                ('strIngredient1', models.CharField(default='null', max_length=100)),
                ('strMeasure1', models.PositiveIntegerField(default='0')),
                ('strIngredient2', models.CharField(default='null', max_length=100)),
                ('strMeasure2', models.PositiveIntegerField(default='0')),
                ('strIngredient3', models.CharField(default='null', max_length=100)),
                ('strMeasure3', models.PositiveIntegerField(default='0')),
                ('strIngredient4', models.CharField(default='null', max_length=100)),
                ('strMeasure4', models.PositiveIntegerField(default='0')),
                ('strIngredient5', models.CharField(default='null', max_length=100)),
                ('strMeasure5', models.PositiveIntegerField(default='0')),
                ('strIngredient6', models.CharField(default='null', max_length=100)),
                ('strMeasure6', models.PositiveIntegerField(default='0')),
                ('imgDrink', models.ImageField(blank='true', upload_to='image/bartender')),
=======
                ('name', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('detail', models.TextField(max_length=300)),
                ('image', models.ImageField(upload_to='')),
>>>>>>> 37eb06a578ddc41ab4f9b67f9ac734e6ce80f0e4
            ],
        ),
        migrations.AddField(
            model_name='ingredient',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe.IngredientCategory'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='recipes',
            field=models.ManyToManyField(to='recipe.Recipe'),
        ),
    ]
