# Generated by Django 2.1.15 on 2020-08-13 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_article_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='base64',
            field=models.TextField(blank=True),
        ),
    ]
