# Generated by Django 2.1.15 on 2020-08-13 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_article_base64'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='base64',
        ),
    ]
